- name: Install dependencies
  ansible.builtin.apt:
    name:
      - wget
      - tar
    state: present

- name: Download latest oauth2-proxy release info
  ansible.builtin.uri:
    url: https://api.github.com/repos/oauth2-proxy/oauth2-proxy/releases/latest
    return_content: true
  register: oauth2_proxy_release
  check_mode: false

- name: Set oauth2-proxy download url
  ansible.builtin.set_fact:
    oauth2_proxy_download_url: >-
      {{ ((oauth2_proxy_release.content | from_json).assets
         | selectattr('name', 'search', 'linux-' ~ oauth2_cpu_version ~ '.tar.gz')
         | list)[0].browser_download_url }}

- name: Download oauth2-proxy
  ansible.builtin.get_url:
    url: "{{ oauth2_proxy_download_url }}"
    dest: /opt/oauth2-proxy.tar.gz
    mode: '0644'

- name: Extract oauth2-proxy
  ansible.builtin.unarchive:
    src: /opt/oauth2-proxy.tar.gz
    dest: /usr/local/bin/
    remote_src: true
    extra_opts: [--strip-components=1]
    creates: /usr/local/bin/oauth2-proxy

- name: Create config directory
  ansible.builtin.file:
    path: /etc/oauth2-proxy
    state: directory
    mode: '0755'

- name: Create templates directory
  ansible.builtin.file:
    path: /etc/oauth2-proxy/custom-templates
    state: directory
    mode: '0755'

- name: Deploy index.html template
  ansible.builtin.template:
    src: index.html.j2
    dest: /etc/oauth2-proxy/custom-templates/index.html
    mode: '0600'
  notify:
    - Restart oauth2-proxy

- name: Deploy allowed accounts file
  ansible.builtin.template:
    src: authenticated-emails.txt.j2
    dest: /etc/oauth2-proxy/authenticated-emails.txt
    mode: '0600'
  notify:
    - Restart oauth2-proxy

- name: Deploy oauth2-proxy config
  ansible.builtin.template:
    src: oauth2-proxy.cfg.j2
    dest: /etc/oauth2-proxy/oauth2-proxy.cfg
    mode: '0600'
  notify:
    - Restart oauth2-proxy

- name: Deploy oauth2-proxy systemd service
  ansible.builtin.template:
    src: oauth2-proxy.service.j2
    dest: /etc/systemd/system/oauth2-proxy.service
    mode: '0644'

- name: Enable and start oauth2-proxy
  ansible.builtin.systemd:
    name: oauth2-proxy
    enabled: true
    state: started
    daemon_reload: true
