- name: Install dependencies
  apt:
    name:
      - wget
      - tar
    state: present

- name: Download oauth2-proxy
  get_url:
    url: "{{ oauth2_proxy_download_url }}"
    dest: /tmp/oauth2-proxy.tar.gz
    mode: '0644'

- name: Extract oauth2-proxy
  unarchive:
    src: /tmp/oauth2-proxy.tar.gz
    dest: /usr/local/bin/
    remote_src: yes
    extra_opts: [--strip-components=1]
    creates: /usr/local/bin/oauth2-proxy

- name: Create config directory
  file:
    path: /etc/oauth2-proxy
    state: directory
    mode: '0755'

- name: Deploy oauth2-proxy config
  template:
    src: oauth2-proxy.cfg.j2
    dest: /etc/oauth2-proxy/oauth2-proxy.cfg
    mode: '0600'

- name: Deploy oauth2-proxy systemd service
  template:
    src: oauth2-proxy.service.j2
    dest: /etc/systemd/system/oauth2-proxy.service
    mode: '0644'

- name: Reload systemd
  systemd:
    daemon_reload: yes

- name: Enable and start oauth2-proxy
  systemd:
    name: oauth2-proxy
    enabled: yes
    state: started