# Generated by Django 2.2.12 on 2020-04-04 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprinklers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprinkler',
            name='sprinkler_active_state',
            field=models.BooleanField(default=False),
        ),
    ]
