# This file is part of the Auto Sprinklers project.

- name: Clone the full repository to a temp folder
  ansible.builtin.git:
    repo: 'https://github.com/fchioralia/autohome.git'
    dest: /tmp/autohome
    version: 'master'
    force: true

- name: Synchronize only the auto_sprinklers folder to the app folder (delete extra files)
  ansible.posix.synchronize:
    src: /tmp/autohome/auto_sprinklers/
    dest: "{{ app_folder }}/"
    delete: true
    recursive: true
    mode: push
    rsync_opts:
      - "--exclude=.git"
  delegate_to: raspberry_pi

- name: Ensure python3-venv is installed
  ansible.builtin.apt:
    name: python3-venv
    state: present

- name: Create virtual environment for Django
  ansible.builtin.command: "python3 -m venv {{ app_environment }} "
  args:
    creates: "{{ app_environment }}"

- name: Upgrade pip in virtualenv
  ansible.builtin.pip:
    name: pip
    virtualenv: "{{ app_environment }}"
    extra_args: --upgrade

- name: Install Django in virtualenv
  ansible.builtin.pip:
    name: django
    virtualenv: "{{ app_environment }}"

- name: Install python-daemon in virtualenv
  ansible.builtin.pip:
    name: python-daemon
    virtualenv: "{{ app_environment }}"

- name: Install rpi-lgpio in virtualenv
  ansible.builtin.pip:
    name: rpi-lgpio
    virtualenv: "{{ app_environment }}"

- name: Install requests in virtualenv
  ansible.builtin.pip:
    name: requests
    virtualenv: "{{ app_environment }}"

- name: Install Gunicorn in Django virtualenv
  ansible.builtin.pip:
    name: gunicorn
    virtualenv: "{{ app_environment }}"

- name: Configure Gunicorn systemd service
  ansible.builtin.template:
    src: gunicorn.service.j2
    dest: /etc/systemd/system/gunicorn.service
    owner: root
    group: root
    mode: '0644'

- name: Enable and start Gunicorn service
  ansible.builtin.systemd:
    name: gunicorn
    enabled: true
    state: started
    daemon_reload: true

- name: Configure autohome service
  ansible.builtin.template:
    src: autohome.service.j2
    dest: /etc/systemd/system/autohome.service
    owner: root
    group: root
    mode: '0644'

- name: Start and enable autohome service
  ansible.builtin.systemd:
    name: autohome
    enabled: true
    state: started
    daemon_reload: true
