---
- name: Configure Raspberry Pi for Auto Sprinklers
  hosts: raspberry
  become: true
  gather_facts: false
  roles:
    - common
    - app
    - role: oauth2_proxy
      when: oauth2_enable | bool
    - webserver
